name: .NET Core

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Zkontrolovat kód
      uses: actions/checkout@v2

    - name: Nastavit .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.x

    - name: Obnovit závislosti
      run: dotnet restore
      working-directory: StrecanskaBackend/ApiTests

    - name: Instalovat coverlet.collector
      run: dotnet add package coverlet.collector
      working-directory: StrecanskaBackend/ApiTests

    - name: Sestavit
      run: dotnet build --no-restore --configuration Release
      working-directory: StrecanskaBackend/ApiTests

    - name: Spustit testy s pokrytím kódu
      run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage"
      working-directory: StrecanskaBackend/ApiTests

    - name: Nahrát pokrytí na Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: StrecanskaBackend/ApiTests/TestResults/**/coverage.cobertura.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
